<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_EmailHomePage</name>
   <tag></tag>
   <elementGuidId>1cf803cc-7b2f-4327-8d8f-1ac66df6d34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Form_submitForm_EmailHomePage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Form_submitForm_EmailHomePage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e1e4970-5c94-43db-834e-0e8983047887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>38371d57-25bd-47e7-acbf-bea72fc4a572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailHomePage</value>
      <webElementGuid>48a8e93d-cfcf-46d6-b9e8-fc262927ab94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email text tryit-email</value>
      <webElementGuid>489c6f3b-e217-4a31-bda0-091df6a437b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Form_submitForm_EmailHomePage</value>
      <webElementGuid>9eff19ca-23a5-4c38-bc82-0247e5711ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a949ab8e-5d71-4634-856f-6c1e42600a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email address here</value>
      <webElementGuid>f1323279-4579-444e-ba2f-f72b60bf1632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form_submitForm_EmailHomePage&quot;)</value>
      <webElementGuid>7b59b38a-bdcf-4810-9ef6-6698c86d8a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Form_submitForm_EmailHomePage']</value>
      <webElementGuid>c8a8d7da-dc60-4498-8560-13b9e63b0509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Form_submitForm_EmailHomePage_Holder']/div/input</value>
      <webElementGuid>9d0f988b-e244-451e-b95c-16ca84f26187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>fbf54b82-29ff-4d83-b71d-52fee0a1fbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'EmailHomePage' and @id = 'Form_submitForm_EmailHomePage' and @placeholder = 'Enter your email address here']</value>
      <webElementGuid>90082e99-6303-4fc1-bafc-43c70c73de50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
